name: Deploy to S3 Bucket

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "yarn"

      - run: yarn install

      - name: Build and deploy
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_SNOWTRACE_API_KEY: ${{ secrets.REACT_APP_SNOWTRACE_API_KEY }}
        run: |
          yarn build
          aws s3 cp ./build s3://mc-speed-limit --recursive
